# Generated by Django 3.0 on 2019-12-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_on_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creation_date', '-updated_on_date'],
            },
        ),
    ]
